### ISSUE TITLE
Is this project MIT-license compatible

### ISSUE THREAD

**Issue by pixtur** [michaelnoonan/inputsimulator#10]
Hi Michael,

is it possible to add the inputsimulator as part of an open-source-project under M.I.T. license if we link to this project page and name your authorship?

BR,
tom

**Comment by john-cullen** [comment]
Hi,

@michaelnoonan  it would be good to get an answer as to what the licence of this project is.

I see there a couple of forks that have added a licence, but (and I am not a lawyer!) that seems legally questionable.

Regards
John Cullen

**Comment by michaelnoonan** [comment]
Hi all. Sorry, I've not paid attention to this library in some time! It's now licensed under MIT.

**Comment by TChatzigiannakis** [comment]
@michaelnoonan On NuGet you had indicated (in 2013) that it is MS-PL licensed. I'm only mentioning this so that you know where the reference to the MS-PL license originates from in some forks (including mine).

**Comment by michaelnoonan** [comment]
Ah, that makes sense. I do recall the original version being shipped via CodePlex with MS-PL. When the code moved to GitHub, I neglected to set a license, meaning the code here was copyright by default.

I'm happy for this to open up to MIT as a more permissive license as long as you are happy to contribute changes from your fork under MIT. The alternative is we change the license of this repository to MS-PL instead of MIT.

**Comment by TChatzigiannakis** [comment]
I personally have no problem with any open source license. I think MIT is a better choice overall.

**Comment by john-cullen** [comment]
Thanks for sorting this out so quickly guys.
